name: docker
on:
  push:
    branches:
      - v2.0
jobs:
  test:
    runs-on: ubuntu-18.04      
    steps:
      - 
        name: checkout
        uses: actions/checkout@v2
      -
        name: build and test
        run: |
          docker build -t openshiftacademiaonline/spring-petclinic-dev:2.0-testing --no-cache .
          docker run -d -p 80:8080 openshiftacademiaonline/spring-petclinic-dev:2.0-testing
          while true
            do
              sleep 1
              docker ps | grep Up && break
            done
          while true
            do
              sleep 1  
              docker ps | grep java && break
            done
          while true
            do
              sleep 1
              curl localhost -I | grep 200 && break
            done
            
              
            
